# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9dfc0d682cb24e73581d43de26c27487"
name = "giftcode"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders,write_gift_cards,write_discounts,read_customers,read_price_rules"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
